insert into tipo_recurso(id,tipo) values(1,'Computador');
insert into tipo_recurso(id,tipo) values(2,'Multimedia');
insert into tipo_recurso(id,tipo) values(3,'Sala de estudio');

insert into usuario(id,passw,tipo,carnet,nombre,carrera) values('regular@cvds.com','03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4','regular',123456,'regular','Ingenieria de sistemas');
insert into usuario(id,passw,tipo,carnet,nombre,carrera) values('admin@cvds.com','03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4','administrador',1234567,'administrador','Administrador');

insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Wrapsafe', 'Biblioteca G', 1, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Domainer', 'Biblioteca B', 2, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Zontrax', 'Biblioteca B', 3, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zathin', 'Biblioteca G', 4, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Keylex', 'Biblioteca B', 5, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Mat Lam Tam', 'Biblioteca G', 6, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Zamit', 'Biblioteca G', 7, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Pannier', 'Biblioteca B', 8, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Toughjoyfax', 'Biblioteca B', 9, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Ronstring', 'Biblioteca G', 10, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Toughjoyfax', 'Biblioteca B', 11, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Bigtax', 'Biblioteca G', 12, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Y-Solowarm', 'Biblioteca G', 13, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Flowdesk', 'Biblioteca G', 14, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Asoka', 'Biblioteca G', 15, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Solarbreeze', 'Biblioteca B', 16, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Tres-Zap', 'Biblioteca G', 17, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Latlux', 'Biblioteca B', 18, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Sonsing', 'Biblioteca B', 19, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Alpha', 'Biblioteca B', 20, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Fix San', 'Biblioteca G', 21, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Voltsillam', 'Biblioteca B', 22, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Kanlam', 'Biblioteca G', 23, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Treeflex', 'Biblioteca B', 24, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Biodex', 'Biblioteca G', 25, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Kanlam', 'Biblioteca B', 26, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Tempsoft', 'Biblioteca B', 27, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Lotstring', 'Biblioteca G', 28, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Tempsoft', 'Biblioteca B', 29, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Overhold', 'Biblioteca B', 30, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zoolab', 'Biblioteca G', 31, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Ventosanzap', 'Biblioteca G', 32, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Tres-Zap', 'Biblioteca G', 33, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Otcom', 'Biblioteca G', 34, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Biodex', 'Biblioteca G', 35, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Ventosanzap', 'Biblioteca G', 36, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Ventosanzap', 'Biblioteca B', 37, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Veribet', 'Biblioteca B', 38, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Gembucket', 'Biblioteca B', 39, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Regrant', 'Biblioteca B', 40, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Alpha', 'Biblioteca B', 41, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Flexidy', 'Biblioteca B', 42, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Span', 'Biblioteca G', 43, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Subin', 'Biblioteca B', 44, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Namfix', 'Biblioteca B', 45, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Y-Solowarm', 'Biblioteca B', 46, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Duobam', 'Biblioteca B', 47, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Latlux', 'Biblioteca G', 48, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Tampflex', 'Biblioteca B', 49, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zamit', 'Biblioteca B', 50, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Aerified', 'Biblioteca G', 51, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Konklab', 'Biblioteca G', 52, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Sonsing', 'Biblioteca B', 53, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Sonsing', 'Biblioteca B', 54, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Cardify', 'Biblioteca B', 55, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Voyatouch', 'Biblioteca B', 56, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Alpha', 'Biblioteca G', 57, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zamit', 'Biblioteca G', 58, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Trippledex', 'Biblioteca B', 59, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Andalax', 'Biblioteca B', 60, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Treeflex', 'Biblioteca B', 61, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Tampflex', 'Biblioteca G', 62, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Wrapsafe', 'Biblioteca B', 63, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Bigtax', 'Biblioteca B', 64, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Greenlam', 'Biblioteca B', 65, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Holdlamis', 'Biblioteca G', 66, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Stim', 'Biblioteca B', 67, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Duobam', 'Biblioteca G', 68, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Overhold', 'Biblioteca B', 69, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Span', 'Biblioteca B', 70, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Ronstring', 'Biblioteca G', 71, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Lotlux', 'Biblioteca G', 72, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Keylex', 'Biblioteca G', 73, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Otcom', 'Biblioteca G', 74, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Keylex', 'Biblioteca B', 75, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Keylex', 'Biblioteca B', 76, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Bitwolf', 'Biblioteca B', 77, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Andalax', 'Biblioteca G', 78, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Gembucket', 'Biblioteca B', 79, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Voyatouch', 'Biblioteca G', 80, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Sonsing', 'Biblioteca G', 81, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Asoka', 'Biblioteca B', 82, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Tres-Zap', 'Biblioteca B', 83, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Stringtough', 'Biblioteca B', 84, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Stronghold', 'Biblioteca B', 85, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Zaam-Dox', 'Biblioteca G', 86, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Biodex', 'Biblioteca G', 87, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Redhold', 'Biblioteca G', 88, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Voltsillam', 'Biblioteca B', 89, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Fintone', 'Biblioteca G', 90, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Cardify', 'Biblioteca G', 91, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Span', 'Biblioteca G', 92, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Home Ing', 'Biblioteca G', 93, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Trippledex', 'Biblioteca B', 94, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Stringtough', 'Biblioteca G', 95, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Lotstring', 'Biblioteca B', 96, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Subin', 'Biblioteca B', 97, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Lotlux', 'Biblioteca B', 98, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Tresom', 'Biblioteca B', 99, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Voyatouch', 'Biblioteca B', 100, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Overhold', 'Biblioteca B', 101, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Sonair', 'Biblioteca G', 102, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Fix San', 'Biblioteca G', 103, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Tres-Zap', 'Biblioteca B', 104, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Subin', 'Biblioteca G', 105, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Sonsing', 'Biblioteca G', 106, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Solarbreeze', 'Biblioteca G', 107, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Bitwolf', 'Biblioteca B', 108, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Stringtough', 'Biblioteca B', 109, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Redhold', 'Biblioteca G', 110, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Lotlux', 'Biblioteca B', 111, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Konklux', 'Biblioteca G', 112, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Otcom', 'Biblioteca G', 113, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Prodder', 'Biblioteca B', 114, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Sonair', 'Biblioteca G', 115, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Solarbreeze', 'Biblioteca G', 116, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zoolab', 'Biblioteca G', 117, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Zontrax', 'Biblioteca G', 118, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Solarbreeze', 'Biblioteca B', 119, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Solarbreeze', 'Biblioteca B', 120, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Biodex', 'Biblioteca B', 121, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Namfix', 'Biblioteca G', 122, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Otcom', 'Biblioteca G', 123, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Regrant', 'Biblioteca G', 124, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Biodex', 'Biblioteca G', 125, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Lotstring', 'Biblioteca B', 126, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Lotlux', 'Biblioteca B', 127, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Redhold', 'Biblioteca B', 128, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Ventosanzap', 'Biblioteca B', 129, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Flexidy', 'Biblioteca G', 130, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Alphazap', 'Biblioteca G', 131, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bytecard', 'Biblioteca G', 132, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Fixflex', 'Biblioteca B', 133, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bitwolf', 'Biblioteca G', 134, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Lotstring', 'Biblioteca B', 135, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Kanlam', 'Biblioteca G', 136, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Tin', 'Biblioteca B', 137, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Pannier', 'Biblioteca B', 138, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bigtax', 'Biblioteca B', 139, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Redhold', 'Biblioteca G', 140, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Biodex', 'Biblioteca G', 141, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Voltsillam', 'Biblioteca B', 142, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Otcom', 'Biblioteca G', 143, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Flowdesk', 'Biblioteca G', 144, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Tempsoft', 'Biblioteca B', 145, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Transcof', 'Biblioteca B', 146, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Job', 'Biblioteca B', 147, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Job', 'Biblioteca B', 148, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Flowdesk', 'Biblioteca B', 149, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Bamity', 'Biblioteca B', 150, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Stronghold', 'Biblioteca B', 151, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Redhold', 'Biblioteca B', 152, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Quo Lux', 'Biblioteca B', 153, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Quo Lux', 'Biblioteca B', 154, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Temp', 'Biblioteca G', 155, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Stim', 'Biblioteca B', 156, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Rank', 'Biblioteca G', 157, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Transcof', 'Biblioteca B', 158, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Home Ing', 'Biblioteca G', 159, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Transcof', 'Biblioteca B', 160, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Latlux', 'Biblioteca B', 161, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Keylex', 'Biblioteca B', 162, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Vagram', 'Biblioteca G', 163, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bigtax', 'Biblioteca G', 164, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Tresom', 'Biblioteca B', 165, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Stringtough', 'Biblioteca B', 166, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Duobam', 'Biblioteca G', 167, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Domainer', 'Biblioteca B', 168, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Greenlam', 'Biblioteca G', 169, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Kanlam', 'Biblioteca B', 170, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Tres-Zap', 'Biblioteca G', 171, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Bitwolf', 'Biblioteca G', 172, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Sub-Ex', 'Biblioteca G', 173, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Stronghold', 'Biblioteca B', 174, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Alpha', 'Biblioteca B', 175, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Prodder', 'Biblioteca G', 176, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Bigtax', 'Biblioteca G', 177, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Greenlam', 'Biblioteca B', 178, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Flexidy', 'Biblioteca G', 179, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Lotlux', 'Biblioteca B', 180, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Latlux', 'Biblioteca B', 181, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Treeflex', 'Biblioteca G', 182, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Tresom', 'Biblioteca B', 183, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Cardguard', 'Biblioteca B', 184, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Lotstring', 'Biblioteca B', 185, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Flexidy', 'Biblioteca G', 186, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Holdlamis', 'Biblioteca B', 187, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Home Ing', 'Biblioteca G', 188, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Y-Solowarm', 'Biblioteca G', 189, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Redhold', 'Biblioteca B', 190, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bigtax', 'Biblioteca B', 191, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Cardify', 'Biblioteca B', 192, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Y-find', 'Biblioteca G', 193, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Stringtough', 'Biblioteca B', 194, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zoolab', 'Biblioteca G', 195, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Alphazap', 'Biblioteca B', 196, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Stim', 'Biblioteca B', 197, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Konklux', 'Biblioteca B', 198, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Y-find', 'Biblioteca B', 199, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Lotlux', 'Biblioteca B', 200, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Bigtax', 'Biblioteca B', 201, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Greenlam', 'Biblioteca B', 202, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Voltsillam', 'Biblioteca B', 203, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Opela', 'Biblioteca G', 204, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zaam-Dox', 'Biblioteca B', 205, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bamity', 'Biblioteca G', 206, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Home Ing', 'Biblioteca B', 207, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Domainer', 'Biblioteca B', 208, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Sonsing', 'Biblioteca B', 209, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Stringtough', 'Biblioteca B', 210, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Veribet', 'Biblioteca B', 211, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Namfix', 'Biblioteca G', 212, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Treeflex', 'Biblioteca G', 213, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'It', 'Biblioteca G', 214, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Stronghold', 'Biblioteca G', 215, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Fix San', 'Biblioteca B', 216, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Ventosanzap', 'Biblioteca B', 217, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Konklab', 'Biblioteca B', 218, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Tin', 'Biblioteca B', 219, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Fixflex', 'Biblioteca G', 220, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Wrapsafe', 'Biblioteca G', 221, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Holdlamis', 'Biblioteca G', 222, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Namfix', 'Biblioteca B', 223, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Viva', 'Biblioteca G', 224, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Holdlamis', 'Biblioteca B', 225, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Opela', 'Biblioteca B', 226, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Bytecard', 'Biblioteca G', 227, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Zaam-Dox', 'Biblioteca B', 228, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Andalax', 'Biblioteca B', 229, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Voyatouch', 'Biblioteca G', 230, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Tresom', 'Biblioteca B', 231, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bitchip', 'Biblioteca G', 232, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Tresom', 'Biblioteca B', 233, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Konklab', 'Biblioteca G', 234, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zontrax', 'Biblioteca G', 235, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Overhold', 'Biblioteca B', 236, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Vagram', 'Biblioteca G', 237, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Zoolab', 'Biblioteca B', 238, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Pannier', 'Biblioteca B', 239, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Fixflex', 'Biblioteca B', 240, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Lotstring', 'Biblioteca G', 241, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Stim', 'Biblioteca G', 242, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Vagram', 'Biblioteca G', 243, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Fixflex', 'Biblioteca G', 244, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Cookley', 'Biblioteca G', 245, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Andalax', 'Biblioteca G', 246, 'No Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Bamity', 'Biblioteca B', 247, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (3, 'Mat Lam Tam', 'Biblioteca B', 248, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (1, 'Veribet', 'Biblioteca G', 249, 'Disponible');
insert into recurso (id_tipo, nombre, ubicacion, capacidad, estado) values (2, 'Zamit', 'Biblioteca G', 250, 'No Disponible');
