CREATE SEQUENCE SUS_TIPO_RECURSO_seq;

CREATE TABLE TIPO_RECURSO
(id integer NOT NULL DEFAULT NEXTVAL('SUS_TIPO_RECURSO_seq'),
tipo VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE RECURSO
(id_interno integer NOT NULL,
id_tipo integer NOT NULL,
nombre VARCHAR(50) NOT NULL,
ubicacion VARCHAR(50) NOT NULL,
capacidad integer,
estado BOOLEAN NOT NULL,
PRIMARY KEY (id_interno)
);

CREATE SEQUENCE SUS_RECURSO_RENTADO_seq

CREATE TABLE RECURSO_RENTADO
(id integer NOT NULL DEFAULT NEXTVAL('SUS_RECURSO_RENTADO_seq'),
fecha_ini DATE NOT NULL,
fecha_fin DATE NOT NULL,
id_recurso integer,
id_usuario VARCHAR(50),
PRIMARY KEY (id)
);

CREATE TABLE USUARIO(
id VARCHAR(50) NOT NULL,
passw VARCHAR(50) NOT NULL,
tipo VARCHAR(50) NOT NULL,
PRIMARY KEY(id)
);